version: '3'

services:
  tomcat:
    image: docker.io/library/tomcat:latest
    container_name: ${container_name}
    tty: true 
    command: >
      sh -c "catalina.sh run"

    ports:
      - '8080-8100:8080'
      #Docker n'incremente pas, il prends des ports de manière aléatoire
    labels:
      - "co.elastic.logs/enabled=true"
      #- "co.elastic.logs/module=nginx"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=Tomcat-${container_name}"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=Tomcat-${container_name}"
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war
      - ./../log:/usr/local/tomcat/logs/
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    networks:
      - elastic

networks:
  elastic:
    external: true
    name: elastic
    
