version: '3'

services:
  tomcat:
    image: docker.io/library/tomcat:latest
    container_name: ${container_name}
    tty: true 
    command: >
      sh -c "catalina.sh run"

    ports:
      - '8080-8100:8080'
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=${container_name}"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=${container_name}"
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war
      - /opt/pod/${container_name}/log:/usr/local/tomcat/logs/
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./logging.properties:/usr/local/tomcat/conf/logging.properties
